project_id = "dxcoanrzxfwrpuhnfayd"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.login-with-userid]
verify_jwt = false

[functions.update-user]
verify_jwt = false
